### ISSUE TITLE
UMLS Authentication not working

### ISSUE THREAD

**Issue by lopsided** [OHDSI/Athena#168]
Hi, 

I've been having this issue for 2 days since I got my account confirmed. I read the related issues #54 and #63 so I keep retrying hoping it is just temporarily offline. But in case not I thought I should create this ticket.

```
$ ./cpt.sh USER PASS
or
$ java -Dumls-user=USER -Dumls-password=PASS -jar ./cpt4.jar 5
```
both give
```
Exception in thread "main" java.lang.RuntimeException: Cannot process CONCEPT.csv file. You can find more details in the logs/logfile.log file. 
Reason: Wrong user/password combination or not enough permissions on your account to execute Java. Please check your privileges.
	at org.odhsi.utils.cpt.Application.main(Application.java:31)
```
And the corresponding log entry:
```
[ERROR] 2020-06-26 18:05:40.665 [main] ApplicationContextServer - Cannot initialize application
gov.nih.nlm.uts.webservice.UtsFault_Exception: Error getting a ticket granting ticket: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_242]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_242]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_242]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_242]
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:117) ~[cpt4.jar:?]
	at com.sun.xml.ws.client.sei.StubHandler.readResponse(StubHandler.java:223) ~[cpt4.jar:?]
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:176) ~[cpt4.jar:?]
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:263) ~[cpt4.jar:?]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89) ~[cpt4.jar:?]
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62) ~[cpt4.jar:?]
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131) ~[cpt4.jar:?]
	at com.sun.proxy.$Proxy54.getProxyGrantTicket(Unknown Source) ~[?:?]
	at org.odhsi.utils.cpt.ApplicationContextServer.init(ApplicationContextServer.java:44) [cpt4.jar:?]
	at org.odhsi.utils.cpt.Application.main(Application.java:27) [cpt4.jar:?]
```

**Comment by acumarav** [comment]
Hello @lopsided, looks like issue caused by the UMLS authentication. Current script might not work if your password contains quot. I will update it to support shielding but may you please try to run current cpt.sh using shielded password which you might generated via e.g.: https://onlinelinuxtools.com/escape-shell-characters

**Comment by lopsided** [comment]
Hi @acumarav I tried escaping the special chars but still had no luck until I reset my password to something simpler, with no need for escaping, and now it works! Thanks
