### ISSUE TITLE
cpt4.jar throws exception

### ISSUE THREAD

**Issue by mik-ohdsi** [OHDSI/Athena#280]
At the end of the CPT4 processing, the cpt4.jar execution presents a couple of exceptions as shown in this [forum thread](https://forums.ohdsi.org/t/java-error-message-when-reconstitue-cpt4/16509).
The exceptions indicate that the UMLS API has been slightly changed and that the API call from the cpt4.jar routines needs to be adapted. 
This issue is related to #258 (API call unsuccessful for a set of concepts) and #268 (remove log4j vulnerability by using newer library version).
As far as we know, the CPT4 reconstitution still is complete despite the exceptions (probably the API call is not properly closed or something).

**Comment by mik-ohdsi** [comment]
sample of the response:
`WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[INFO ] 2022-05-13 17:39:25.539 [main] ConceptService - Writing updated data to CONCEPT.csv
Updated CPT4 records:  16615/16615
[INFO ] 2022-05-13 17:57:25.356 [main] ConceptService - All cpt4 concepts are processed.
Exception in thread "main" org.odhsi.utils.cpt.Cpt4Exception: Unexpected code Response{protocol=http/1.1, code=401, message=Unauthorized, url=https://utslogin.nlm.nih.gov//cas/v1/tickets/TGT-244082-30dyni05l34lurev-cas}
        at org.odhsi.utils.cpt.restclient.RestTicketClient.checkSuccessful(RestTicketClient.java:76)
        at org.odhsi.utils.cpt.restclient.RestTicketClient.logout(RestTicketClient.java:113)
        at org.odhsi.utils.cpt.restclient.RestTicketClient.close(RestTicketClient.java:125)
        at org.odhsi.utils.cpt.Application.main(Application.java:49)`

**Comment by Siddhesh-Nalawade** [comment]
@mik-ohdsi 

Is there any alternate way to solve this error? Could you please suggest any other option to load CPT4 concepts?

**Comment by mik-ohdsi** [comment]
@Siddhesh-Nalawade , as stated in the forum post, you should still be able to load / complement the CPT4 concepts, regardless of that error message AFTER the CPT34 concepts had been reconstituted.

**Comment by mik-ohdsi** [comment]
The Exception has been fixed with the latest version. Thank you!
