### ISSUE TITLE
CONCEPT_CPT4.csv file issues

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/Athena#3]
Greetings,

There is a small issue with the CONCEPT_CPT4.csv needing to be renamed to lowercase for cpt4.jar to work properly. If running as-is the program throws an error:

<code>
java -jar cpt4.jar
java.io.FileNotFoundException: ./concept_cpt4.csv (No such file or directory)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:146)
        at java.io.FileInputStream.<init>(FileInputStream.java:101)
        at java.io.FileReader.<init>(FileReader.java:58)
        at org.odhsi.Main.main(Main.java:34)
Update failed. .csv file not found.
</code>

A quick rename to lowercase fixes the issue.

**Comment by GlebMalikov** [comment]
Done.

**Comment by jmbanda** [comment]
Thanks!
