### ISSUE TITLE
cpt4.jar doesn't rerun on linux

### ISSUE THREAD

**Issue by barashe** [OHDSI/Athena#323]
When running cpt4.jar on linux, as in issue #322 some CPT4 concepts are not mapped. However, unlike the solution discussed in #322, when running cpt.jar again, there's an error when trying to read/write to logs/logfile.log:

```` bash
[INFO ] 2022-12-20 15:08:29.405 [main] ConceptService - Not processed cpt4 concepts: 11961. See logs/not-processed-concepts-12-20-2022-14-47-42.out, file. You can find more information about errors in the logs/logfile.log file 
~ ./cpt.sh <api-key>                                                                                             
[INFO ] 2022-12-20 15:08:40.459 [main] ConceptService - Writing updated data to CONCEPT.csv                                                                                                                                        
2022-12-20 15:08:40,462 main ERROR Unable to write to stream logs/logfile.log for appender File_Appender org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to stream logs/logfile.log                 
        at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:252)                                                                                                             
        at org.apache.logging.log4j.core.appender.FileManager.writeToDestination(FileManager.java:277)                                                                                                                             
        at org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:283)                                                                                                                    
        at org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:294)                                                                                                                          
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)                                                                                            
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)                                                                                                    
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)                                                                                                       
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)                                                                                                                          
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)                                                                                                                            
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)                                                                                                             
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)                                                                                                                              
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)                                                                                                                                  
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)                                                                                                                                
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)                                                                                                                                            
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)                                                                                                                                      
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)                                                                                                                                
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)                                                                                                                                            
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)                                                                                                                                            
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)                                                                                                 
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)                                                                                                                                                               
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)                                                                                                                                     
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)                                                                                                                          
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)                                                                                                                                  
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2022)                                                                                                                                        
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1875)                                                                                                                                      
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:179)                                                                                                                                                         
        at org.odhsi.utils.cpt.services.ConceptService.process(ConceptService.java:29)                                                                                                                                             
        at org.odhsi.utils.cpt.Application.main(Application.java:40)                                                                                                                                                               
Caused by: java.io.IOException: Operation not supported                                                                                                                                                                            
        at java.io.FileOutputStream.writeBytes(Native Method)                                                                                                                                                                      
        at java.io.FileOutputStream.write(FileOutputStream.java:326)                                                                                                                                                               
        at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:250)                                                                                                             
        ... 27 more

2022-12-20 15:08:40,464 main ERROR An exception occurred processing Appender File_Appender org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to stream logs/logfile.log
        at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:252)
        at org.apache.logging.log4j.core.appender.FileManager.writeToDestination(FileManager.java:277)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:283)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:294)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:199)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:190)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:181)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.logParent(LoggerConfig.java:533)
        at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:502)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)
        at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
        at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:82)
        at org.apache.logging.log4j.core.Logger.log(Logger.java:161)
        at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2205)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2159)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2142)
        at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2022)
        at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1875)
        at org.apache.logging.slf4j.Log4jLogger.info(Log4jLogger.java:179)
        at org.odhsi.utils.cpt.services.ConceptService.process(ConceptService.java:29)
        at org.odhsi.utils.cpt.Application.main(Application.java:40)
Caused by: java.io.IOException: Operation not supported
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:250)
        ... 27 more

^C2022-12-20 15:08:43,305 pool-1-thread-1 ERROR FileManager logs/logfile.log Unable to close stream: java.io.IOException: Operation not supported java.io.IOException: Operation not supported
        at java.io.FileOutputStream.close0(Native Method)
        at java.io.FileOutputStream.access$000(FileOutputStream.java:53)
        at java.io.FileOutputStream$1.close(FileOutputStream.java:356)
        at java.io.FileDescriptor.closeAll(FileDescriptor.java:212)
        at java.io.FileOutputStream.close(FileOutputStream.java:354)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.closeOutputStream(OutputStreamManager.java:305)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.releaseSub(OutputStreamManager.java:122)
        at org.apache.logging.log4j.core.appender.AbstractManager.stop(AbstractManager.java:87)
        at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.stop(AbstractOutputStreamAppender.java:162)
        at org.apache.logging.log4j.core.appender.FileAppender.stop(FileAppender.java:284)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.stop(AbstractConfiguration.java:403)
        at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:392)
        at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:320)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:119)
        at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:78)
        at java.lang.Thread.run(Thread.java:748)
````

cpt4.jar keeps on running, but starts from scratch instead of mapping only the unmapped concepts. Essentially, this causes the script to never fully map all CPT4 concepts. 
This is the java version used:

```` bash
~ java -version
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Zulu 8.56.0.21-CA-linux64) (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Zulu 8.56.0.21-CA-linux64) (build 25.302-b08, mixed mode)
````

Ubuntu 20.04.5 LTS

**Comment by mik-ohdsi** [comment]
thanks, @barashe  -  that is a bummer. We will try to fix the root cause of it as soon as possible, as fixing your issue will probably take the same amount of time.

**Comment by mik-ohdsi** [comment]
@barashe - can you try the newer version of the tool in Linux (you need to request a new vocab download). It runs slower though (+5 hours).

**Comment by konstjar** [comment]
Closed due to no response
