### ISSUE TITLE
Error when unpacking V5 CPT4 files

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/Athena#4]
I requested V5 vocabulary files from Athena and I unzipped them and attempted to unpack the CPT4 codes. When I opened the command lines and ran "java -jar cpt4.jar" I received this error:

```
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/odhsi/Mai
n : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$000(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
Could not find the main class: org.odhsi.Main. Program will exit.
```

Thanks,
Clair

**Comment by clairblacketer** [comment]
Fixed it- my version of Java was out of date.
